### ISSUE TITLE
phantom+mcfost: segmentation faults for simulations with more than 16 cores

### ISSUE THREAD

**Issue by Pedro73** [cpinte/mcfost#103]
Segmentation faults appear when more than 16 cores are considered for a phantom+mcfost simulation. 

The error

`Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`

is repeated as many times as extra cores overpass that limit. The only way to avoid the error is to define

```export OMP_NUM_THREADS=16``` (or less)

Of course, the variables
```
ulimit -s unlimited
export SYSTEM=gfortran
export OMP_SCHEDULE="dynamic"
export OMP_STACKSIZE=2048M
```

were set.

**Comment by Pedro73** [comment]
Hi Christophe,

In my laptop, I use the pre-cooked configuration "disc" in PHANTOM, although I have also used "dustydisc". Plus, `export MCFOST=yes`. The rest of the options are the default ones.

These are the input files (the .csv only for uploading here). I use a reduced number of particles in my laptop to run it faster, but I have tested it in a cluster with more particles with the same result. 

[disc.para.csv](https://github.com/cpinte/mcfost/files/14405577/disc.para.csv)
[disc.in.csv](https://github.com/cpinte/mcfost/files/14405578/disc.in.csv)
[disc.setup.csv](https://github.com/cpinte/mcfost/files/14405579/disc.setup.csv)

This is the entire error message. Note I received 4 segmentation faults due to the use of 20 cores. 

![Screenshot from 2024-02-26 14-48-41](https://github.com/cpinte/mcfost/assets/20848444/33e829b7-caa0-41dd-ac87-840fc4ac0d61)

**Comment by Pedro73** [comment]
Both codes are in their latest versions

**Comment by cpinte** [comment]
Hi Pedro,
Can you try in debug mode to get a more detailed error message ?
I have tried again on both mac and linux, and it works perfectly in both cases. I am a bit confused.

**Comment by Pedro73** [comment]
There are the output files.

[err.txt](https://github.com/cpinte/mcfost/files/14512868/err.txt)
[out.txt](https://github.com/cpinte/mcfost/files/14512869/out.txt)

**Comment by cpinte** [comment]
Thanks.
This confirms that it is an issue in the phantom tree. I don't think there is anything that I can fix on the mcfost side as it seems to return a temperature structure as expected to phantom.
I think the best is to lodge an issue on the phantom github as Daniel might have a better idea.

**Comment by danieljprice** [comment]
I think this is an issue with not having set OMP_STACKSIZE correctly
