### ISSUE TITLE
Obtaining UV fluxes for a Phantom dump

### ISSUE THREAD

**Issue by alisonkyoung1** [cpinte/mcfost#107]
I would like to obtain a fits file of UV fluxes when running Mcfost on a Phantom dump. -output_UV_field doesn't seem to be implemented for a Voronoi grid so I tried adding in code similar to that for making Temperature.fits.gz but then it crashes elsewhere. What are the essential things to add to get this to work? I'm not sure if UV wavelengths are only added in if the Prodimo/chemistry flags are used too?

**Comment by cpinte** [comment]
Hi Alison,
Ok, I will try to add this asap.

**Comment by cpinte** [comment]
This should now be fixed with commit [cdbec1d](https://github.com/cpinte/mcfost/commit/cdbec1da45aa389d579b4940b4d1b048b786951d)
