### ISSUE TITLE
gfortran internal compiler error on Atoms/opacity.f90

### ISSUE THREAD

**Issue by danieljprice** [cpinte/mcfost#23]
Further attempt to compile AtomicTransfer branch with gfortran produces ICE:
```
Compiling MCFOST for gfortran system...........

gfortran -m64 -cpp -O3 -funroll-loops -ffinite-math-only -fno-trapping-math -fbacktrace -fopenmp -c -DPOINTER_SIZE=8 Atoms/opacity.f90 -o Atoms/opacity.o -I/usr/local/include
f951: internal compiler error: Segmentation fault: 11
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make: *** [Atoms/opacity.o] Error 1
```
This is likely a gfortran problem, but I got it down to the following line:
```
    if (.not.associated(profile, local_profile_interp)) then
```
which seems innocent, but hides a huge amount of complexity, going down a crazy rabbit hole:

- profile is a procedure pointer to something with the same interface as local_profile_v
- local_profile_interp is a function with the same interface as local_profile_v
- BUT the interface to local_profile_v contains a derived type:
```
		type (AtomicLine), intent(in)								:: line
```
...which is a huge derived type with 1,2,4 and 5 dimensional allocatable arrays, character strings and ALSO contains two other derived types:
```
 TYPE AtomicLine
   ...
  type (AtomType), pointer :: atom => NULL()
  type (ZeemanType) :: zm
```

AtomType is another complicated derived type, but the weird thing is that it ALSO contains AtomicLine part of its type definition:
```
 TYPE AtomType
   ...
   type (AtomicLine), allocatable, dimension(:)         :: lines
```
so I think the underlying problem here is that there is a recursive type definition. Is this allowed?

I will try to get this down to a simpler problem to report to the gfortran folks, but the above already suggests something fishy in the mcfost code...

**Comment by cpinte** [comment]
Fixed in gcc v12:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100892
