### ISSUE TITLE
build-and-test issues

### ISSUE THREAD

**Issue by btessore** [cpinte/mcfost#80]
build-and-test(linux,ifort,yes) and (linux,ifort,no) did not pass because of a docker error on pull request 71

The test stops at "the initialize containers" with the following error message:

```
 failed to register layer: write /opt/intel/oneapi/vtune/2023.2.0/target/android_v5/sepdkinternal-only/src/socperf/src/inc/pmu_info_mmio.h: no space left on device
  Error: Docker pull failed with exit code 1
```

**Comment by bmsykes** [comment]
This should be fixed by https://github.com/cpinte/mcfost/pull/78 which removes the need for that container.

**Comment by cpinte** [comment]
This does look fixed indeed, thanks @bmsykes !
